In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml
from sklearn import preprocessing
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
X,Y = fetch_openml('iris',version= 1,return_X_y= True)

In [3]:
type(X)

numpy.ndarray

In [4]:
print("shape of X",X.shape)
print("shape of Y",Y.shape)
print(X[:10])
print(Y[:10])
# 1. sepal length in cm
# 2. sepal width in cm
# 3. petal length in cm
# 4. petal width in cm

shape of X (150, 4)
shape of Y (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [5]:
class cat_deal:
    def __init__(self):
        self.max_len = 0#不同个数 0是nan嘛所以从1开始算
        self.dict_map = {}
    
    def fit(self,cat_list):
        index = 1
        for cat_i in cat_list:
            if cat_i not in self.dict_map:
                self.dict_map[cat_i]  = index
                index += 1
        self.max_len = index + 1#保险一点怕有异常值
    
    def transform (self,cat_list):
        cat_transform_list = []
        for cat_i in cat_list:
            if cat_i in self.dict_map:
                cat_transform_list.append(self.dict_map[cat_i])
            else:
                cat_transform_list.append(0)
        return cat_transform_list

In [17]:
Y = Y.reshape(len(Y),-1)#需要reshape成列向量
dict_cat_class = {}
i = 0
dict_cat_class[i] = cat_deal()
dict_cat_class[i].fit(Y[:,i])
Y[:,i] = dict_cat_class[i].transform(Y[:,i])
Y = Y.reshape(len(Y))
Y = Y.astype(int)
print(Y.shape)
print(Y.dtype)

(150,)
int64


In [18]:
trainX,testX,trainY,testY = train_test_split(X,Y,train_size = 120,test_size = 30,random_state = 233)
trainY

array([1, 2, 2, 2, 2, 1, 3, 2, 3, 3, 3, 1, 2, 3, 1, 2, 1, 3, 1, 3, 1, 3,
       3, 2, 2, 3, 3, 2, 3, 3, 1, 1, 1, 3, 1, 2, 2, 1, 3, 3, 2, 3, 1, 3,
       3, 2, 3, 2, 3, 1, 2, 1, 2, 2, 3, 2, 1, 2, 2, 2, 3, 3, 3, 1, 2, 2,
       3, 1, 3, 3, 1, 1, 1, 1, 1, 2, 1, 3, 2, 2, 1, 3, 3, 3, 3, 1, 1, 1,
       1, 1, 3, 3, 2, 1, 1, 1, 2, 2, 3, 2, 2, 3, 1, 1, 3, 1, 3, 1, 2, 2,
       1, 1, 2, 2, 2, 1, 2, 3, 3, 1])

In [20]:
gnb = GaussianNB().fit(trainX,trainY)
val_acc = gnb.score(testX,testY)
val_acc

0.9333333333333333